### ISSUE TITLE
What is pltt?

### ISSUE THREAD

**Issue by unixorn** [hendrixfan/pltt-zsh-plugin#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I couldn't figure out what pltt is.

Thanks!

**Comment by hendrixfan** [comment]
pltt is a time tracking tool we use at work (works similar to [gtt](https://github.com/kriskbx/gitlab-time-tracker)). It's a proprietary tool just for me and my colleagues. 
I guess it wouldn't make much sense to add it to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins).

Thanks anyway
